### ISSUE TITLE
Allow for discontinous shorelines to be mapped

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#155] opened 2023-06-13 18:12 UTC
In the original version of coastsat shorelines have to be continuous, which can result in the extracted shorelines having a stitching effect to combine multiple discontinuous shorelines together as shown in the image below. Coastseg should  allow for multiple discontinuous shorelines to be extracted from a single image without artificially stitching the shorelines together.
![image (4)](https://github.com/Doodleverse/CoastSeg/assets/61564689/a5ed4afe-169f-428f-91f6-5f9c549b8fa6)

Here are a few ideas to start with
1. Allowing multiple reference shorelines to be uploaded.
2. Informing the users to expand the reference Shoreline buffer
3. Modifying the algorithm that creates the extracted shorelines to create multiple discontinuous shorelines

**Comment by dbuscombe-usgs** [comment] 2023-07-26 17:36
closing this as a duplicate of https://github.com/Doodleverse/CoastSeg/issues/163

**Closed by dbuscombe-usgs** 2023-07-26 17:36 UTC
Labels: enhancement, V2
